# Stage 1: Build
FROM node:22-slim AS builder

ENV CI=true
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Install build tools for native modules
RUN apt-get update && apt-get install -y openssl python3 make g++ && rm -rf /var/lib/apt/lists/*
RUN corepack enable

WORKDIR /app

# Install dependencies (cached)
COPY pnpm-lock.yaml package.json ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Copy source and build
COPY . .
RUN npx prisma generate
RUN pnpm run build

# Clean up the output to prevent duplicate node_modules in the final copy
# We will install fresh production-only modules in the next stage
RUN rm -rf .output/server/node_modules

# Stage 2: Production Dependencies (Temporary)
# We use this stage to install ONLY the dependencies needed by the output server
# This avoids installing 'nuxt' and other build-time dependencies in the final image
FROM node:22-slim AS prod-deps
RUN apt-get update && apt-get install -y openssl python3 make g++ && rm -rf /var/lib/apt/lists/*
WORKDIR /app

# Copy the server package.json generated by Nitro
COPY --from=builder /app/.output/server/package.json ./package.json

# Install ONLY production dependencies (no devDependencies, no Nuxt core)
# This installs better-sqlite3 and builds it natively
# We use --legacy-peer-deps because better-auth 1.4.x has a strict peer dependency on Prisma 5.x
# but we are using Prisma 7.x which is compatible but strictly version-locked in package.json
RUN npm install --omit=dev --legacy-peer-deps

# Stage 3: Final Image
FROM node:22-slim

# Valid openssl is required for prisma/database
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV NODE_ENV=production

# Copy the built application from builder (without node_modules)
COPY --from=builder /app/.output ./.output

# Copy the PRODUCTION dependencies from the prod-deps stage
# This gives us a clean, minimal node_modules with compiled native addons
COPY --from=prod-deps /app/node_modules ./.output/server/node_modules

# Copy the generated Prisma Client
COPY --from=builder /app/prisma/generated ./prisma/generated

# Copy the prisma schema AND the committed migrations (issue #33) so the
# entrypoint can run `prisma migrate deploy` against the production DB at start.
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts

# Install ONLY the prisma CLI (+ dotenv, which prisma.config.ts loads) into the
# app root so `prisma migrate deploy` can run at container start. Pinned to the
# project's Prisma version. This is separate from the app's runtime deps in
# .output/server/node_modules (which carry @prisma/client but not the CLI).
RUN npm install --no-save prisma@7.2.0 dotenv@17.2.3

# Apply any pending migrations, then start the server (see docker-entrypoint.sh).
COPY docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod +x ./docker-entrypoint.sh

EXPOSE 3000

CMD ["./docker-entrypoint.sh"]
