# Stage 1: Build
FROM node:22-slim AS builder

ENV CI=true
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Install build tools for native modules
RUN apt-get update && apt-get install -y openssl python3 make g++ && rm -rf /var/lib/apt/lists/*
RUN corepack enable

WORKDIR /app

# Install dependencies (cached)
COPY pnpm-lock.yaml package.json ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Copy source and build
COPY . .
RUN npx prisma generate
RUN pnpm run build

# Clean up the output to prevent duplicate node_modules in the final copy
# We will install fresh production-only modules in the next stage
RUN rm -rf .output/server/node_modules

# Stage 2: Production Dependencies (Temporary)
# We use this stage to install ONLY the dependencies needed by the output server
# This avoids installing 'nuxt' and other build-time dependencies in the final image
FROM node:22-slim AS prod-deps
RUN apt-get update && apt-get install -y openssl python3 make g++ && rm -rf /var/lib/apt/lists/*
WORKDIR /app

# Copy the server package.json generated by Nitro
COPY --from=builder /app/.output/server/package.json ./package.json

# Install ONLY production dependencies (no devDependencies, no Nuxt core)
# This installs better-sqlite3 and builds it natively
RUN npm install --omit=dev

# Stage 3: Final Image
FROM node:22-slim

# Valid openssl is required for prisma/database
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV NODE_ENV=production

# Copy the built application from builder (without node_modules)
COPY --from=builder /app/.output ./.output

# Copy the PRODUCTION dependencies from the prod-deps stage
# This gives us a clean, minimal node_modules with compiled native addons
COPY --from=prod-deps /app/node_modules ./.output/server/node_modules

# Copy the generated Prisma Client
COPY --from=builder /app/prisma/generated ./prisma/generated

# Copy prisma schema just in case it's needed for runtime validations or migrations
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
